### ISSUE TITLE
Endpoint to verify OTP 

### ISSUE THREAD

**Issue by yhoungdev** [Bookhive-Club/Bookhive-backend#1]
Look into the Schema. 

create an edpoint to verify OTP
* navigate to controller/auth/create-your-filename.ts for verify OTP 

Note follow the codebase structure. 
endpoint route should be /api/auth/verify_otp

just like this 
![Screenshot from 2023-10-04 13-42-25](https://github.com/Bookhive-Club/Bookhive-backend/assets/54102389/21b6bb2e-9488-4404-aabd-60298507cc47)

**Comment by yhoungdev** [comment]
Hey @Rahul-jain-01 yea sure.

**Comment by yhoungdev** [comment]
Hey @Rahul-jain-01  how are you going with this ?

**Comment by Rahul-jain-01** [comment]
> Hey @Rahul-jain-01  how are you going with this ?

Hey, thanks for asking. But I'm not able to test any end points. Could you please help me with that.

**Comment by yhoungdev** [comment]
yea sure, whats the issue you are having testing. 

  do you mind if i send the Api Collection ?

**Comment by Rahul-jain-01** [comment]
> yea sure, whats the issue you are having testing. 
> 
>   do you mind if i send the Api Collection ?

I'm using thunderbolt to test it but its showing the "connection was forcibly closed by a peer".

Yeahh sure please do send the api collection. 

Thank you.

**Comment by yhoungdev** [comment]
Can i see the error message you are reciving ?

**Comment by Rahul-jain-01** [comment]
![Error](https://github.com/Bookhive-Club/Bookhive-backend/assets/71962320/48a90f5a-834a-46c7-914b-ad4b032f329e)

**Comment by yhoungdev** [comment]
you need the databse connection string. i will send that to you

**Comment by Rahul-jain-01** [comment]
> you need the databse connection string. i will send that to you

Yeah sure, thank you

**Comment by yhoungdev** [comment]
yea thanks

**Comment by Rahul-jain-01** [comment]
Hey @yhoungdev I debugged the errors I was getting and now I wanted to show you the code snippet to verify OTP.
Can you check out, please!!
![Snippet1](https://github.com/Bookhive-Club/Bookhive-backend/assets/71962320/94815bf8-ca70-4d59-8c4a-57d7af08c864)
![Snippet2](https://github.com/Bookhive-Club/Bookhive-backend/assets/71962320/59423600-6308-438e-b807-3682f3867c76)

**Comment by yhoungdev** [comment]
Hey man this is sweet. 

  can i chat you up ??

**Comment by Rahul-jain-01** [comment]
> Hey man this is sweet. 
> 
>   can i chat you up ??

Yeah sure!!
How about Discord?

**Comment by Rahul-jain-01** [comment]
> nice send me a message @obiabo

I have sent a request.

**Comment by yhoungdev** [comment]
sent a message
